// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wegeexfuvagvyntbtcyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZ2VleGZ1dmFndnludGJ0Y3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjI3OTcsImV4cCI6MjA1ODUzODc5N30.7OFFeKGnUFxTthJxrfy-J6LciaKY-IvaozHCPTEbSjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);